Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.network "private_network", ip: "192.168.1.2"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y default-jdk xauth
  SHELL

  config.vm.provision "file", source: "./src/main/java", destination: "/home/vagrant/myapp"
  config.ssh.forward_x11 = true

  config.vm.provision "shell", inline: <<-SHELL
    echo "if [[ -z \\"$DISPLAY\\" && \\"${SSH_CONNECTION}\\" ]]; then
      export DISPLAY=\$(echo \$SSH_CONNECTION | cut -d ' ' -f 1):0.0
      cd /home/vagrant/myapp
      javac *.java
      java -cp . Main &
    fi" >> /home/vagrant/.bash_profile
  SHELL
end
